# Site settings
title: EVEREST POST
email: producers@everestpost.co.nz
description: >-
  Everest Post provides high-quality post-production services including audio,
  picture, DIT, remote connectivity, and editing facilities for film and television.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.everestpost.co.nz" # the base hostname & protocol for your site
phone: "+64 29 043 01156"
address: "56A SWAINSTON ROAD, AUCKLAND, NEW ZEALAND"

# Site version
version: "1.0.0"

# API Keys (these will be overridden by environment variables in production)
hcaptcha_site_key: "10000000-ffff-ffff-ffff-000000000001" # Development key
google_maps_api_key: "YOUR_DEVELOPMENT_KEY"
tmdb_api_key: "YOUR_DEVELOPMENT_TMDB_KEY" # TMDB API key
formspree_form_id: "YOUR_DEVELOPMENT_FORMSPREE_ID" # Formspree form ID

# Build settings
markdown: kramdown
permalink: /:title/

# Collections
collections:
  secondary_portfolio:
    output: false
  clients:
    output: false
  footer_logos:
    output: false

# Minification
sass:
  sass_dir: _sass
  style: compressed

# Plugins
plugins:
  - jekyll-minifier

# Minifier settings
jekyll-minifier:
  exclude: ['*.xml', '*.json', 'robots.txt']
  js_compressor: uglifier
  compress_css: true
  compress_javascript: true
  html_compressor: htmlcompressor
  preserve_line_breaks: false
  remove_intertag_spaces: true
  remove_comments: true
  simple_doctype: false
  compress_json: false
